name: Run Tests

on:
  push:
    branches:
      - main
      - '**' # Run on all branches
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install --index-url https://acc-py-repo.cern.ch/repository/vr-py-releases/simple pytimber

      # Run tests
      - name: Run tests
        run: |
          PYTHONPATH=src pytest tests/test_analysis.py